/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_affichage2 (void)
{
  GtkWidget *affichage2;
  GtkWidget *fixed1;
  GtkWidget *treeview2;
  GtkWidget *entry115;
  GtkWidget *label1;
  GtkWidget *afficher2_reclamation;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image3;
  GtkWidget *label188;
  GtkWidget *retour;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image4;
  GtkWidget *label189;
  GtkWidget *supprimer2;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label190;
  GtkWidget *label186;
  GtkWidget *image2;
  GtkWidget *label191;

  affichage2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage2), _("affichage2"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (affichage2), fixed1);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview2, 24, 56);
  gtk_widget_set_size_request (treeview2, 488, 256);

  entry115 = gtk_entry_new ();
  gtk_widget_show (entry115);
  gtk_fixed_put (GTK_FIXED (fixed1), entry115, 136, 392);
  gtk_widget_set_size_request (entry115, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry115), 8226);

  label1 = gtk_label_new_with_mnemonic (_("<span size=\"xx-large\"  foreground=\"blue\" background=\"white\"style =\"italic\"><b>TOUS LES RECLAMATIONS</b></span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 80, 8);
  gtk_widget_set_size_request (label1, 344, 32);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  afficher2_reclamation = gtk_button_new ();
  gtk_widget_show (afficher2_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher2_reclamation, 328, 320);
  gtk_widget_set_size_request (afficher2_reclamation, 82, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (afficher2_reclamation), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image3 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox1), image3, FALSE, FALSE, 0);

  label188 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label188);
  gtk_box_pack_start (GTK_BOX (hbox1), label188, FALSE, FALSE, 0);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed1), retour, 416, 320);
  gtk_widget_set_size_request (retour, 80, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (retour), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox2), image4, FALSE, FALSE, 0);

  label189 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label189);
  gtk_box_pack_start (GTK_BOX (hbox2), label189, FALSE, FALSE, 0);

  supprimer2 = gtk_button_new ();
  gtk_widget_show (supprimer2);
  gtk_fixed_put (GTK_FIXED (fixed1), supprimer2, 304, 392);
  gtk_widget_set_size_request (supprimer2, 104, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (supprimer2), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label190 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label190);
  gtk_box_pack_start (GTK_BOX (hbox3), label190, FALSE, FALSE, 0);

  label186 = gtk_label_new ("");
  gtk_widget_show (label186);
  gtk_fixed_put (GTK_FIXED (fixed1), label186, 96, 424);
  gtk_widget_set_size_request (label186, 304, 25);

  image2 = create_pixmap (affichage2, "index.jpeg");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed1), image2, 64, 456);
  gtk_widget_set_size_request (image2, 368, 168);

  label191 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" background=\"white\"><b><u>RECLAMATION</u></b></span>\n"));
  gtk_widget_show (label191);
  gtk_fixed_put (GTK_FIXED (fixed1), label191, 16, 392);
  gtk_widget_set_size_request (label191, 112, 16);
  gtk_label_set_use_markup (GTK_LABEL (label191), TRUE);

  g_signal_connect ((gpointer) afficher2_reclamation, "clicked",
                    G_CALLBACK (on_afficher2_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer2, "clicked",
                    G_CALLBACK (on_supprimer2_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label191), entry115);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage2, affichage2, "affichage2");
  GLADE_HOOKUP_OBJECT (affichage2, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (affichage2, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (affichage2, entry115, "entry115");
  GLADE_HOOKUP_OBJECT (affichage2, label1, "label1");
  GLADE_HOOKUP_OBJECT (affichage2, afficher2_reclamation, "afficher2_reclamation");
  GLADE_HOOKUP_OBJECT (affichage2, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (affichage2, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (affichage2, image3, "image3");
  GLADE_HOOKUP_OBJECT (affichage2, label188, "label188");
  GLADE_HOOKUP_OBJECT (affichage2, retour, "retour");
  GLADE_HOOKUP_OBJECT (affichage2, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (affichage2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (affichage2, image4, "image4");
  GLADE_HOOKUP_OBJECT (affichage2, label189, "label189");
  GLADE_HOOKUP_OBJECT (affichage2, supprimer2, "supprimer2");
  GLADE_HOOKUP_OBJECT (affichage2, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (affichage2, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (affichage2, image5, "image5");
  GLADE_HOOKUP_OBJECT (affichage2, label190, "label190");
  GLADE_HOOKUP_OBJECT (affichage2, label186, "label186");
  GLADE_HOOKUP_OBJECT (affichage2, image2, "image2");
  GLADE_HOOKUP_OBJECT (affichage2, label191, "label191");

  return affichage2;
}

GtkWidget*
create_modification2 (void)
{
  GtkWidget *modification2;
  GtkWidget *fixed2;
  GtkWidget *entry116;
  GtkWidget *entry118;
  GtkWidget *image1;
  GtkWidget *label187;
  GtkWidget *recherche2_reclamation;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label192;
  GtkWidget *modifier2_reclamation;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label193;
  GtkWidget *retour2_admin;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label194;
  GtkWidget *label195;
  GtkWidget *frame1;
  GtkWidget *alignment7;
  GtkWidget *label197;
  GtkWidget *label196;
  GtkWidget *label4;

  modification2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modification2, 600, 800);
  gtk_window_set_title (GTK_WINDOW (modification2), _("modification2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (modification2), fixed2);
  GTK_WIDGET_SET_FLAGS (fixed2, GTK_CAN_FOCUS);

  entry116 = gtk_entry_new ();
  gtk_widget_show (entry116);
  gtk_fixed_put (GTK_FIXED (fixed2), entry116, 288, 8);
  gtk_widget_set_size_request (entry116, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry116), 8226);

  entry118 = gtk_entry_new ();
  gtk_widget_show (entry118);
  gtk_fixed_put (GTK_FIXED (fixed2), entry118, 72, 328);
  gtk_widget_set_size_request (entry118, 432, 136);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry118), 8226);

  image1 = create_pixmap (modification2, "index.jpeg");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed2), image1, 144, 536);
  gtk_widget_set_size_request (image1, 288, 176);

  label187 = gtk_label_new ("");
  gtk_widget_show (label187);
  gtk_fixed_put (GTK_FIXED (fixed2), label187, 112, 504);
  gtk_widget_set_size_request (label187, 368, 24);

  recherche2_reclamation = gtk_button_new ();
  gtk_widget_show (recherche2_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), recherche2_reclamation, 456, 8);
  gtk_widget_set_size_request (recherche2_reclamation, 96, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (recherche2_reclamation), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label192 = gtk_label_new_with_mnemonic (_("recherche"));
  gtk_widget_show (label192);
  gtk_box_pack_start (GTK_BOX (hbox4), label192, FALSE, FALSE, 0);

  modifier2_reclamation = gtk_button_new ();
  gtk_widget_show (modifier2_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), modifier2_reclamation, 344, 472);
  gtk_widget_set_size_request (modifier2_reclamation, 88, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (modifier2_reclamation), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label193 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label193);
  gtk_box_pack_start (GTK_BOX (hbox5), label193, FALSE, FALSE, 0);

  retour2_admin = gtk_button_new ();
  gtk_widget_show (retour2_admin);
  gtk_fixed_put (GTK_FIXED (fixed2), retour2_admin, 440, 472);
  gtk_widget_set_size_request (retour2_admin, 72, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (retour2_admin), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label194 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label194);
  gtk_box_pack_start (GTK_BOX (hbox6), label194, FALSE, FALSE, 0);

  label195 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" background=\"white\"><b><u>RECLAMATION</u></b></span>\n"));
  gtk_widget_show (label195);
  gtk_fixed_put (GTK_FIXED (fixed2), label195, 168, 16);
  gtk_widget_set_size_request (label195, 110, 17);
  gtk_label_set_use_markup (GTK_LABEL (label195), TRUE);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_fixed_put (GTK_FIXED (fixed2), frame1, 32, 80);
  gtk_widget_set_size_request (frame1, 480, 184);
  gtk_frame_set_shadow_type (GTK_FRAME (frame1), GTK_SHADOW_NONE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (frame1), alignment7);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment7), 0, 0, 12, 0);

  label197 = gtk_label_new (_("<span foreground=\"black\" background=\"white\"><b>RECLAMATION</b></span>"));
  gtk_widget_show (label197);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label197);
  gtk_label_set_use_markup (GTK_LABEL (label197), TRUE);

  label196 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" background=\"white\"><b><u>RECLAMATION</u></b></span>\n"));
  gtk_widget_show (label196);
  gtk_fixed_put (GTK_FIXED (fixed2), label196, 40, 296);
  gtk_widget_set_size_request (label196, 112, 17);
  gtk_label_set_use_markup (GTK_LABEL (label196), TRUE);

  label4 = gtk_label_new ("");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 56, 104);
  gtk_widget_set_size_request (label4, 416, 152);
  gtk_label_set_width_chars (GTK_LABEL (label4), 5);

  g_signal_connect ((gpointer) recherche2_reclamation, "clicked",
                    G_CALLBACK (on_recherche2_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier2_reclamation, "clicked",
                    G_CALLBACK (on_modifier2_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour2_admin, "clicked",
                    G_CALLBACK (on_retour2_admin_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modification2, modification2, "modification2");
  GLADE_HOOKUP_OBJECT (modification2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (modification2, entry116, "entry116");
  GLADE_HOOKUP_OBJECT (modification2, entry118, "entry118");
  GLADE_HOOKUP_OBJECT (modification2, image1, "image1");
  GLADE_HOOKUP_OBJECT (modification2, label187, "label187");
  GLADE_HOOKUP_OBJECT (modification2, recherche2_reclamation, "recherche2_reclamation");
  GLADE_HOOKUP_OBJECT (modification2, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (modification2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (modification2, image6, "image6");
  GLADE_HOOKUP_OBJECT (modification2, label192, "label192");
  GLADE_HOOKUP_OBJECT (modification2, modifier2_reclamation, "modifier2_reclamation");
  GLADE_HOOKUP_OBJECT (modification2, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (modification2, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (modification2, image7, "image7");
  GLADE_HOOKUP_OBJECT (modification2, label193, "label193");
  GLADE_HOOKUP_OBJECT (modification2, retour2_admin, "retour2_admin");
  GLADE_HOOKUP_OBJECT (modification2, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modification2, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modification2, image8, "image8");
  GLADE_HOOKUP_OBJECT (modification2, label194, "label194");
  GLADE_HOOKUP_OBJECT (modification2, label195, "label195");
  GLADE_HOOKUP_OBJECT (modification2, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (modification2, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modification2, label197, "label197");
  GLADE_HOOKUP_OBJECT (modification2, label196, "label196");
  GLADE_HOOKUP_OBJECT (modification2, label4, "label4");

  gtk_widget_grab_focus (label4);
  return modification2;
}

