/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajouterdevis (void)
{
  GtkWidget *ajouterdevis;
  GtkWidget *fixed1;
  GtkWidget *entry200;
  GtkWidget *label2;
  GtkWidget *entry201;
  GtkWidget *entry203;
  GtkWidget *label1;
  GtkWidget *entry202;
  GtkWidget *label4;
  GtkWidget *entry204;
  GtkWidget *entry205;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *entry206;
  GtkWidget *label3;
  GtkWidget *afficher_devis;
  GtkWidget *ajout_devis;

  ajouterdevis = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouterdevis), _("ajouterdevis"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajouterdevis), fixed1);

  entry200 = gtk_entry_new ();
  gtk_widget_show (entry200);
  gtk_fixed_put (GTK_FIXED (fixed1), entry200, 184, 48);
  gtk_widget_set_size_request (entry200, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry200), 8226);

  label2 = gtk_label_new (_("identifiant du devis"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 24, 88);
  gtk_widget_set_size_request (label2, 152, 24);

  entry201 = gtk_entry_new ();
  gtk_widget_show (entry201);
  gtk_fixed_put (GTK_FIXED (fixed1), entry201, 184, 88);
  gtk_widget_set_size_request (entry201, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry201), 8226);

  entry203 = gtk_entry_new ();
  gtk_widget_show (entry203);
  gtk_fixed_put (GTK_FIXED (fixed1), entry203, 184, 176);
  gtk_widget_set_size_request (entry203, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry203), 8226);

  label1 = gtk_label_new (_("identifiant du client "));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 16, 48);
  gtk_widget_set_size_request (label1, 160, 24);

  entry202 = gtk_entry_new ();
  gtk_widget_show (entry202);
  gtk_fixed_put (GTK_FIXED (fixed1), entry202, 184, 128);
  gtk_widget_set_size_request (entry202, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry202), 8226);

  label4 = gtk_label_new (_("date"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 64, 128);
  gtk_widget_set_size_request (label4, 88, 24);

  entry204 = gtk_entry_new ();
  gtk_widget_show (entry204);
  gtk_fixed_put (GTK_FIXED (fixed1), entry204, 184, 224);
  gtk_widget_set_size_request (entry204, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry204), 8226);

  entry205 = gtk_entry_new ();
  gtk_widget_show (entry205);
  gtk_fixed_put (GTK_FIXED (fixed1), entry205, 184, 272);
  gtk_widget_set_size_request (entry205, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry205), 8226);

  label5 = gtk_label_new (_("montant "));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 48, 224);
  gtk_widget_set_size_request (label5, 112, 24);

  label6 = gtk_label_new (_("code promo"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 40, 272);
  gtk_widget_set_size_request (label6, 112, 24);

  label7 = gtk_label_new (_("total"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 88, 320);
  gtk_widget_set_size_request (label7, 41, 17);

  entry206 = gtk_entry_new ();
  gtk_widget_show (entry206);
  gtk_fixed_put (GTK_FIXED (fixed1), entry206, 184, 312);
  gtk_widget_set_size_request (entry206, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry206), 8226);

  label3 = gtk_label_new (_("type de prestation"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 24, 176);
  gtk_widget_set_size_request (label3, 144, 24);

  afficher_devis = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (afficher_devis);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher_devis, 384, 384);
  gtk_widget_set_size_request (afficher_devis, 66, 29);

  ajout_devis = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (ajout_devis);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_devis, 312, 384);
  gtk_widget_set_size_request (ajout_devis, 66, 29);

  g_signal_connect ((gpointer) afficher_devis, "clicked",
                    G_CALLBACK (on_afficher_devis_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_devis, "clicked",
                    G_CALLBACK (on_ajout_devis_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouterdevis, ajouterdevis, "ajouterdevis");
  GLADE_HOOKUP_OBJECT (ajouterdevis, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajouterdevis, entry200, "entry200");
  GLADE_HOOKUP_OBJECT (ajouterdevis, label2, "label2");
  GLADE_HOOKUP_OBJECT (ajouterdevis, entry201, "entry201");
  GLADE_HOOKUP_OBJECT (ajouterdevis, entry203, "entry203");
  GLADE_HOOKUP_OBJECT (ajouterdevis, label1, "label1");
  GLADE_HOOKUP_OBJECT (ajouterdevis, entry202, "entry202");
  GLADE_HOOKUP_OBJECT (ajouterdevis, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajouterdevis, entry204, "entry204");
  GLADE_HOOKUP_OBJECT (ajouterdevis, entry205, "entry205");
  GLADE_HOOKUP_OBJECT (ajouterdevis, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajouterdevis, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajouterdevis, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajouterdevis, entry206, "entry206");
  GLADE_HOOKUP_OBJECT (ajouterdevis, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajouterdevis, afficher_devis, "afficher_devis");
  GLADE_HOOKUP_OBJECT (ajouterdevis, ajout_devis, "ajout_devis");

  return ajouterdevis;
}

GtkWidget*
create_wind2 (void)
{
  GtkWidget *wind2;
  GtkWidget *fixed3;
  GtkWidget *fixed4;
  GtkWidget *treeview200;
  GtkWidget *entry209;
  GtkWidget *label10;
  GtkWidget *supprimerdevis;
  GtkWidget *button210;
  GtkWidget *label9;
  GtkWidget *modifierdevis;
  GtkWidget *buttonfactures;

  wind2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wind2), _("wind2"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (wind2), fixed3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_fixed_put (GTK_FIXED (fixed3), fixed4, 272, 224);
  gtk_widget_set_size_request (fixed4, 50, 50);

  treeview200 = gtk_tree_view_new ();
  gtk_widget_show (treeview200);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview200, 72, 72);
  gtk_widget_set_size_request (treeview200, 352, 240);

  entry209 = gtk_entry_new ();
  gtk_widget_show (entry209);
  gtk_fixed_put (GTK_FIXED (fixed3), entry209, 160, 368);
  gtk_widget_set_size_request (entry209, 136, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry209), 8226);

  label10 = gtk_label_new (_("saisir l'identifiant du devis"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 136, 336);
  gtk_widget_set_size_request (label10, 184, 32);

  supprimerdevis = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (supprimerdevis);
  gtk_fixed_put (GTK_FIXED (fixed3), supprimerdevis, 344, 368);
  gtk_widget_set_size_request (supprimerdevis, 82, 32);

  button210 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button210);
  gtk_fixed_put (GTK_FIXED (fixed3), button210, 392, 432);
  gtk_widget_set_size_request (button210, 72, 32);

  label9 = gtk_label_new (_("DEVIS"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 192, 24);
  gtk_widget_set_size_request (label9, 96, 32);

  modifierdevis = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifierdevis);
  gtk_fixed_put (GTK_FIXED (fixed3), modifierdevis, 304, 432);
  gtk_widget_set_size_request (modifierdevis, 88, 32);

  buttonfactures = gtk_button_new_with_mnemonic (_("factures"));
  gtk_widget_show (buttonfactures);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonfactures, 224, 432);
  gtk_widget_set_size_request (buttonfactures, 82, 32);

  g_signal_connect ((gpointer) supprimerdevis, "clicked",
                    G_CALLBACK (on_supprimerdevis_clicked),
                    NULL);
  g_signal_connect ((gpointer) button210, "clicked",
                    G_CALLBACK (on_button210_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierdevis, "clicked",
                    G_CALLBACK (on_modifierdevis_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonfactures, "clicked",
                    G_CALLBACK (on_buttonfactures_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wind2, wind2, "wind2");
  GLADE_HOOKUP_OBJECT (wind2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (wind2, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (wind2, treeview200, "treeview200");
  GLADE_HOOKUP_OBJECT (wind2, entry209, "entry209");
  GLADE_HOOKUP_OBJECT (wind2, label10, "label10");
  GLADE_HOOKUP_OBJECT (wind2, supprimerdevis, "supprimerdevis");
  GLADE_HOOKUP_OBJECT (wind2, button210, "button210");
  GLADE_HOOKUP_OBJECT (wind2, label9, "label9");
  GLADE_HOOKUP_OBJECT (wind2, modifierdevis, "modifierdevis");
  GLADE_HOOKUP_OBJECT (wind2, buttonfactures, "buttonfactures");

  return wind2;
}

GtkWidget*
create_wind3 (void)
{
  GtkWidget *wind3;
  GtkWidget *fixed5;
  GtkWidget *label11;
  GtkWidget *entry211;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *entry212;
  GtkWidget *entry213;
  GtkWidget *label200;
  GtkWidget *modifierpromo;
  GtkWidget *modifiertotal;
  GtkWidget *rechercherdevis1;
  GtkWidget *button211;

  wind3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wind3), _("wind3"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (wind3), fixed5);

  label11 = gtk_label_new (_("id_devis"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed5), label11, 8, 40);
  gtk_widget_set_size_request (label11, 88, 32);

  entry211 = gtk_entry_new ();
  gtk_widget_show (entry211);
  gtk_fixed_put (GTK_FIXED (fixed5), entry211, 128, 40);
  gtk_widget_set_size_request (entry211, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry211), 8226);

  label13 = gtk_label_new (_("code_promo"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed5), label13, 8, 168);
  gtk_widget_set_size_request (label13, 112, 24);

  label14 = gtk_label_new (_("total"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed5), label14, 16, 208);
  gtk_widget_set_size_request (label14, 88, 24);

  entry212 = gtk_entry_new ();
  gtk_widget_show (entry212);
  gtk_fixed_put (GTK_FIXED (fixed5), entry212, 128, 168);
  gtk_widget_set_size_request (entry212, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry212), 8226);

  entry213 = gtk_entry_new ();
  gtk_widget_show (entry213);
  gtk_fixed_put (GTK_FIXED (fixed5), entry213, 128, 208);
  gtk_widget_set_size_request (entry213, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry213), 8226);

  label200 = gtk_label_new ("");
  gtk_widget_show (label200);
  gtk_fixed_put (GTK_FIXED (fixed5), label200, 48, 96);
  gtk_widget_set_size_request (label200, 312, 40);

  modifierpromo = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifierpromo);
  gtk_fixed_put (GTK_FIXED (fixed5), modifierpromo, 304, 168);
  gtk_widget_set_size_request (modifierpromo, 80, 32);

  modifiertotal = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifiertotal);
  gtk_fixed_put (GTK_FIXED (fixed5), modifiertotal, 304, 208);
  gtk_widget_set_size_request (modifiertotal, 80, 32);

  rechercherdevis1 = gtk_button_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (rechercherdevis1);
  gtk_fixed_put (GTK_FIXED (fixed5), rechercherdevis1, 304, 40);
  gtk_widget_set_size_request (rechercherdevis1, 88, 32);

  button211 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button211);
  gtk_fixed_put (GTK_FIXED (fixed5), button211, 328, 304);
  gtk_widget_set_size_request (button211, 82, 29);

  g_signal_connect ((gpointer) modifierpromo, "clicked",
                    G_CALLBACK (on_modifierpromo_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifiertotal, "clicked",
                    G_CALLBACK (on_modifiertotal_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercherdevis1, "clicked",
                    G_CALLBACK (on_rechercherdevis1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button211, "clicked",
                    G_CALLBACK (on_button211_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wind3, wind3, "wind3");
  GLADE_HOOKUP_OBJECT (wind3, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (wind3, label11, "label11");
  GLADE_HOOKUP_OBJECT (wind3, entry211, "entry211");
  GLADE_HOOKUP_OBJECT (wind3, label13, "label13");
  GLADE_HOOKUP_OBJECT (wind3, label14, "label14");
  GLADE_HOOKUP_OBJECT (wind3, entry212, "entry212");
  GLADE_HOOKUP_OBJECT (wind3, entry213, "entry213");
  GLADE_HOOKUP_OBJECT (wind3, label200, "label200");
  GLADE_HOOKUP_OBJECT (wind3, modifierpromo, "modifierpromo");
  GLADE_HOOKUP_OBJECT (wind3, modifiertotal, "modifiertotal");
  GLADE_HOOKUP_OBJECT (wind3, rechercherdevis1, "rechercherdevis1");
  GLADE_HOOKUP_OBJECT (wind3, button211, "button211");

  return wind3;
}

GtkWidget*
create_wind10 (void)
{
  GtkWidget *wind10;
  GtkWidget *fixed6;
  GtkWidget *treeviewf;
  GtkWidget *label201;
  GtkWidget *retourwind2;

  wind10 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wind10), _("wind10"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (wind10), fixed6);

  treeviewf = gtk_tree_view_new ();
  gtk_widget_show (treeviewf);
  gtk_fixed_put (GTK_FIXED (fixed6), treeviewf, 48, 72);
  gtk_widget_set_size_request (treeviewf, 300, 200);

  label201 = gtk_label_new (_("FACTURES"));
  gtk_widget_show (label201);
  gtk_fixed_put (GTK_FIXED (fixed6), label201, 144, 24);
  gtk_widget_set_size_request (label201, 112, 24);

  retourwind2 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (retourwind2);
  gtk_fixed_put (GTK_FIXED (fixed6), retourwind2, 304, 312);
  gtk_widget_set_size_request (retourwind2, 82, 29);

  g_signal_connect ((gpointer) retourwind2, "clicked",
                    G_CALLBACK (on_retourwind2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wind10, wind10, "wind10");
  GLADE_HOOKUP_OBJECT (wind10, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (wind10, treeviewf, "treeviewf");
  GLADE_HOOKUP_OBJECT (wind10, label201, "label201");
  GLADE_HOOKUP_OBJECT (wind10, retourwind2, "retourwind2");

  return wind10;
}

