/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_login (void)
{
  GtkWidget *login;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label1;
  GtkWidget *label7;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;

  login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (login, 500, 500);
  gtk_window_set_title (GTK_WINDOW (login), _("Login"));
  gtk_window_set_position (GTK_WINDOW (login), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (login), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (login), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 128, 160);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 128, 200);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);

  label1 = gtk_label_new (_("Password : "));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 16, 192);
  gtk_widget_set_size_request (label1, 104, 40);

  label7 = gtk_label_new (_("Username : "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 16, 152);
  gtk_widget_set_size_request (label7, 104, 40);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 192, 272);
  gtk_widget_set_size_request (button2, 88, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Login"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 192, 336);
  gtk_widget_set_size_request (button1, 88, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("<span foreground=\"red\"><b>User Introuvable !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 176, 16);
  gtk_widget_set_size_request (label4, 128, 64);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  label5 = gtk_label_new (_("<span foreground=\"red\"><b>Entrez votre username!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 288, 136);
  gtk_widget_set_size_request (label5, 176, 64);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  label6 = gtk_label_new (_("<span foreground=\"red\"><b>Entrez votre mot de passe !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 296, 176);
  gtk_widget_set_size_request (label6, 192, 72);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_LoginEspaceEmploye_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login, login, "login");
  GLADE_HOOKUP_OBJECT (login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (login, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (login, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (login, label1, "label1");
  GLADE_HOOKUP_OBJECT (login, label7, "label7");
  GLADE_HOOKUP_OBJECT (login, button2, "button2");
  GLADE_HOOKUP_OBJECT (login, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (login, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (login, image2, "image2");
  GLADE_HOOKUP_OBJECT (login, label3, "label3");
  GLADE_HOOKUP_OBJECT (login, button1, "button1");
  GLADE_HOOKUP_OBJECT (login, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (login, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (login, image1, "image1");
  GLADE_HOOKUP_OBJECT (login, label2, "label2");
  GLADE_HOOKUP_OBJECT (login, label4, "label4");
  GLADE_HOOKUP_OBJECT (login, label5, "label5");
  GLADE_HOOKUP_OBJECT (login, label6, "label6");

  return login;
}

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed2;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label9;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label11;
  GtkWidget *button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label13;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label10;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label12;
  GtkWidget *button26;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label134;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (acceuil, 600, 700);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("Acceuil"));
  gtk_window_set_position (GTK_WINDOW (acceuil), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (acceuil), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed2);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 808, 688);
  gtk_widget_set_size_request (button3, 136, 61);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 184, 120);
  gtk_widget_set_size_request (button4, 208, 62);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Gestion Hebergement"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 176, 344);
  gtk_widget_set_size_request (button6, 208, 62);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Gestion Facture"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox6), label11, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed2), button8, 184, 568);
  gtk_widget_set_size_request (button8, 208, 62);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Gestion Voyage"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox8), label13, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 184, 224);
  gtk_widget_set_size_request (button5, 208, 62);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Gestion Excursion"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 184, 464);
  gtk_widget_set_size_request (button7, 208, 62);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Gestion Location"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox7), label12, FALSE, FALSE, 0);

  button26 = gtk_button_new ();
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed2), button26, 8, 8);
  gtk_widget_set_size_request (button26, 88, 56);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button26), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label134 = gtk_label_new_with_mnemonic (_("LogOut"));
  gtk_widget_show (label134);
  gtk_box_pack_start (GTK_BOX (hbox26), label134, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_AcceuilExcursion_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_AcceuilLocation_clicked),
                    NULL);
  g_signal_connect ((gpointer) button26, "clicked",
                    G_CALLBACK (on_logout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (acceuil, button3, "button3");
  GLADE_HOOKUP_OBJECT (acceuil, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (acceuil, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (acceuil, image3, "image3");
  GLADE_HOOKUP_OBJECT (acceuil, label8, "label8");
  GLADE_HOOKUP_OBJECT (acceuil, button4, "button4");
  GLADE_HOOKUP_OBJECT (acceuil, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (acceuil, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (acceuil, image4, "image4");
  GLADE_HOOKUP_OBJECT (acceuil, label9, "label9");
  GLADE_HOOKUP_OBJECT (acceuil, button6, "button6");
  GLADE_HOOKUP_OBJECT (acceuil, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (acceuil, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (acceuil, image6, "image6");
  GLADE_HOOKUP_OBJECT (acceuil, label11, "label11");
  GLADE_HOOKUP_OBJECT (acceuil, button8, "button8");
  GLADE_HOOKUP_OBJECT (acceuil, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (acceuil, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (acceuil, image8, "image8");
  GLADE_HOOKUP_OBJECT (acceuil, label13, "label13");
  GLADE_HOOKUP_OBJECT (acceuil, button5, "button5");
  GLADE_HOOKUP_OBJECT (acceuil, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (acceuil, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (acceuil, image5, "image5");
  GLADE_HOOKUP_OBJECT (acceuil, label10, "label10");
  GLADE_HOOKUP_OBJECT (acceuil, button7, "button7");
  GLADE_HOOKUP_OBJECT (acceuil, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (acceuil, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (acceuil, image7, "image7");
  GLADE_HOOKUP_OBJECT (acceuil, label12, "label12");
  GLADE_HOOKUP_OBJECT (acceuil, button26, "button26");
  GLADE_HOOKUP_OBJECT (acceuil, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (acceuil, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (acceuil, image26, "image26");
  GLADE_HOOKUP_OBJECT (acceuil, label134, "label134");

  return acceuil;
}

GtkWidget*
create_excursion (void)
{
  GtkWidget *excursion;
  GtkWidget *fixed3;
  GtkWidget *button10;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label15;
  GtkWidget *button9;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label14;
  GtkWidget *notebook1;
  GtkWidget *fixed4;
  GtkWidget *entry3;
  GtkWidget *calendar1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label22;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *label16;
  GtkWidget *label24;
  GtkWidget *label21;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label25;
  GtkWidget *combobox1;
  GtkWidget *label26;
  GtkWidget *label62;
  GtkWidget *combobox4;
  GtkWidget *label63;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *label129;
  GtkWidget *label23;
  GtkWidget *label65;
  GtkWidget *label64;
  GtkWidget *label66;
  GtkWidget *button11;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label18;
  GtkWidget *label27;
  GtkWidget *fixed5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label67;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *label71;
  GtkWidget *label70;
  GtkWidget *label69;
  GtkWidget *label68;
  GtkWidget *entry11;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *button12;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label33;
  GtkWidget *label35;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkWidget *label72;
  GtkWidget *button13;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label34;
  GtkWidget *label36;
  GtkWidget *combobox5;
  GtkWidget *combobox6;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkWidget *label130;
  GtkWidget *label131;
  GtkWidget *button15;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label73;
  GtkWidget *label38;
  GtkWidget *label132;
  GtkWidget *label37;
  GtkWidget *label133;
  GtkWidget *label39;

  excursion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (excursion, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (excursion), _("Gestion Excursion"));
  gtk_window_set_position (GTK_WINDOW (excursion), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (excursion), FALSE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (excursion), fixed3);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed3), button10, 888, 648);
  gtk_widget_set_size_request (button10, 96, 53);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button10), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox10), label15, FALSE, FALSE, 0);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed3), button9, 16, 648);
  gtk_widget_set_size_request (button9, 96, 53);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox9), label14, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed3), notebook1, 0, 8);
  gtk_widget_set_size_request (notebook1, 1016, 640);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3, 272, 112);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed4), calendar1, 224, 248);
  gtk_widget_set_size_request (calendar1, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 776, 256);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  label22 = gtk_label_new (_("Id : "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 64, 104);
  gtk_widget_set_size_request (label22, 80, 48);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 264, 464);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 264, 528);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label16 = gtk_label_new (_("Date  : "));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 56, 288);
  gtk_widget_set_size_request (label16, 128, 48);

  label24 = gtk_label_new (_("Heure : "));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 40, 456);
  gtk_widget_set_size_request (label24, 144, 48);

  label21 = gtk_label_new (_("<span foreground=\"blue\"><i>Excursion ajout\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 40, 24);
  gtk_widget_set_size_request (label21, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  label19 = gtk_label_new (_("<span foreground=\"red\"><b>Excursion existant!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 320, 24);
  gtk_widget_set_size_request (label19, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Id !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 440, 88);
  gtk_widget_set_size_request (label20, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label25 = gtk_label_new (_("Depart : "));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 32, 144);
  gtk_widget_set_size_request (label25, 128, 48);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox1, 272, 152);
  gtk_widget_set_size_request (combobox1, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Monastir"));

  label26 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir depart !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 440, 128);
  gtk_widget_set_size_request (label26, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label62 = gtk_label_new (_("Destination : "));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed4), label62, 32, 200);
  gtk_widget_set_size_request (label62, 128, 48);

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox4, 272, 208);
  gtk_widget_set_size_request (combobox4, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Parie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Rome"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Barcelone"));

  label63 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir destination !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label63, 440, 192);
  gtk_widget_set_size_request (label63, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label63), TRUE);

  spinbutton9_adj = gtk_adjustment_new (200, 200, 1200, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton9, 776, 304);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  label129 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label129);
  gtk_fixed_put (GTK_FIXED (fixed4), label129, 672, 296);
  gtk_widget_set_size_request (label129, 120, 40);

  label23 = gtk_label_new (_("Nombre de place dispo : "));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 584, 248);
  gtk_widget_set_size_request (label23, 184, 40);

  label65 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Heure !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label65, 384, 440);
  gtk_widget_set_size_request (label65, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  label64 = gtk_label_new (_("Moyen de transport  : "));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed4), label64, 0, 512);
  gtk_widget_set_size_request (label64, 144, 48);

  label66 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Moyen de transport !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label66, 416, 504);
  gtk_widget_set_size_request (label66, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed4), button11, 728, 392);
  gtk_widget_set_size_request (button11, 96, 53);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button11), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox11), label18, FALSE, FALSE, 0);

  label27 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label27);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label27);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  spinbutton6_adj = gtk_adjustment_new (200, 200, 1200, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton6, 808, 416);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label67 = gtk_label_new (_("Depart : "));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed5), label67, 640, 96);
  gtk_widget_set_size_request (label67, 128, 48);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed5), entry9, 768, 208);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed5), entry10, 768, 256);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label71 = gtk_label_new (_("Moyen de transport  : "));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed5), label71, 600, 296);
  gtk_widget_set_size_request (label71, 144, 48);

  label70 = gtk_label_new (_("Heure : "));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed5), label70, 648, 248);
  gtk_widget_set_size_request (label70, 144, 48);

  label69 = gtk_label_new (_("Date  : "));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed5), label69, 656, 200);
  gtk_widget_set_size_request (label69, 128, 48);

  label68 = gtk_label_new (_("Destination : "));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed5), label68, 632, 144);
  gtk_widget_set_size_request (label68, 128, 48);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed5), entry11, 768, 304);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 0, 80);
  gtk_widget_set_size_request (scrolledwindow1, 584, 384);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 584, 384);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed5), button12, 64, 512);
  gtk_widget_set_size_request (button12, 104, 56);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button12), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox12), label33, FALSE, FALSE, 0);

  label35 = gtk_label_new (_("Modifier l'Excursion : "));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed5), label35, 656, 56);
  gtk_widget_set_size_request (label35, 152, 48);

  spinbutton10_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton10, 808, 368);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  label72 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed5), label72, 672, 408);
  gtk_widget_set_size_request (label72, 120, 40);

  button13 = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed5), button13, 800, 480);
  gtk_widget_set_size_request (button13, 96, 53);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button13), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox13), label34, FALSE, FALSE, 0);

  label36 = gtk_label_new ("");
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed5), label36, 824, 56);
  gtk_widget_set_size_request (label36, 104, 48);

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox5, 768, 104);
  gtk_widget_set_size_request (combobox5, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Monastir"));

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox6, 768, 152);
  gtk_widget_set_size_request (combobox6, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Parie"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Rome"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Barcelone"));

  spinbutton11_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton11, 408, 528);
  gtk_widget_set_size_request (spinbutton11, 60, 27);

  label130 = gtk_label_new (_("NB place Dispo : "));
  gtk_widget_show (label130);
  gtk_fixed_put (GTK_FIXED (fixed5), label130, 632, 360);
  gtk_widget_set_size_request (label130, 120, 40);

  label131 = gtk_label_new (_("NB place Dispo : "));
  gtk_widget_show (label131);
  gtk_fixed_put (GTK_FIXED (fixed5), label131, 280, 520);
  gtk_widget_set_size_request (label131, 120, 40);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed5), button15, 488, 512);
  gtk_widget_set_size_request (button15, 104, 56);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button15), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox15), label73, FALSE, FALSE, 0);

  label38 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner une Excursion !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 0, 16);
  gtk_widget_set_size_request (label38, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label132 = gtk_label_new (_("<span foreground=\"red\"><b>Nombre Invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label132, 320, 472);
  gtk_widget_set_size_request (label132, 136, 48);
  gtk_label_set_use_markup (GTK_LABEL (label132), TRUE);

  label37 = gtk_label_new (_("<span foreground=\"blue\"><i>Excursion modifi\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 664, 0);
  gtk_widget_set_size_request (label37, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label133 = gtk_label_new (_("<span foreground=\"blue\"><i>Reservation reussite</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label133, 344, 0);
  gtk_widget_set_size_request (label133, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label133), TRUE);

  label39 = gtk_label_new (_("Afficher/Supprimer/Modifier"));
  gtk_widget_show (label39);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label39);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_ExcursionAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_AjouterExcursion_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_SupprimerExcursion_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_ModifierExcursion_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_ReserverExcursion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (excursion, excursion, "excursion");
  GLADE_HOOKUP_OBJECT (excursion, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (excursion, button10, "button10");
  GLADE_HOOKUP_OBJECT (excursion, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (excursion, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (excursion, image10, "image10");
  GLADE_HOOKUP_OBJECT (excursion, label15, "label15");
  GLADE_HOOKUP_OBJECT (excursion, button9, "button9");
  GLADE_HOOKUP_OBJECT (excursion, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (excursion, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (excursion, image9, "image9");
  GLADE_HOOKUP_OBJECT (excursion, label14, "label14");
  GLADE_HOOKUP_OBJECT (excursion, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (excursion, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (excursion, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (excursion, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (excursion, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (excursion, label22, "label22");
  GLADE_HOOKUP_OBJECT (excursion, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (excursion, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (excursion, label16, "label16");
  GLADE_HOOKUP_OBJECT (excursion, label24, "label24");
  GLADE_HOOKUP_OBJECT (excursion, label21, "label21");
  GLADE_HOOKUP_OBJECT (excursion, label19, "label19");
  GLADE_HOOKUP_OBJECT (excursion, label20, "label20");
  GLADE_HOOKUP_OBJECT (excursion, label25, "label25");
  GLADE_HOOKUP_OBJECT (excursion, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (excursion, label26, "label26");
  GLADE_HOOKUP_OBJECT (excursion, label62, "label62");
  GLADE_HOOKUP_OBJECT (excursion, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (excursion, label63, "label63");
  GLADE_HOOKUP_OBJECT (excursion, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (excursion, label129, "label129");
  GLADE_HOOKUP_OBJECT (excursion, label23, "label23");
  GLADE_HOOKUP_OBJECT (excursion, label65, "label65");
  GLADE_HOOKUP_OBJECT (excursion, label64, "label64");
  GLADE_HOOKUP_OBJECT (excursion, label66, "label66");
  GLADE_HOOKUP_OBJECT (excursion, button11, "button11");
  GLADE_HOOKUP_OBJECT (excursion, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (excursion, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (excursion, image11, "image11");
  GLADE_HOOKUP_OBJECT (excursion, label18, "label18");
  GLADE_HOOKUP_OBJECT (excursion, label27, "label27");
  GLADE_HOOKUP_OBJECT (excursion, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (excursion, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (excursion, label67, "label67");
  GLADE_HOOKUP_OBJECT (excursion, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (excursion, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (excursion, label71, "label71");
  GLADE_HOOKUP_OBJECT (excursion, label70, "label70");
  GLADE_HOOKUP_OBJECT (excursion, label69, "label69");
  GLADE_HOOKUP_OBJECT (excursion, label68, "label68");
  GLADE_HOOKUP_OBJECT (excursion, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (excursion, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (excursion, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (excursion, button12, "button12");
  GLADE_HOOKUP_OBJECT (excursion, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (excursion, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (excursion, image12, "image12");
  GLADE_HOOKUP_OBJECT (excursion, label33, "label33");
  GLADE_HOOKUP_OBJECT (excursion, label35, "label35");
  GLADE_HOOKUP_OBJECT (excursion, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (excursion, label72, "label72");
  GLADE_HOOKUP_OBJECT (excursion, button13, "button13");
  GLADE_HOOKUP_OBJECT (excursion, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (excursion, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (excursion, image13, "image13");
  GLADE_HOOKUP_OBJECT (excursion, label34, "label34");
  GLADE_HOOKUP_OBJECT (excursion, label36, "label36");
  GLADE_HOOKUP_OBJECT (excursion, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (excursion, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (excursion, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (excursion, label130, "label130");
  GLADE_HOOKUP_OBJECT (excursion, label131, "label131");
  GLADE_HOOKUP_OBJECT (excursion, button15, "button15");
  GLADE_HOOKUP_OBJECT (excursion, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (excursion, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (excursion, image15, "image15");
  GLADE_HOOKUP_OBJECT (excursion, label73, "label73");
  GLADE_HOOKUP_OBJECT (excursion, label38, "label38");
  GLADE_HOOKUP_OBJECT (excursion, label132, "label132");
  GLADE_HOOKUP_OBJECT (excursion, label37, "label37");
  GLADE_HOOKUP_OBJECT (excursion, label133, "label133");
  GLADE_HOOKUP_OBJECT (excursion, label39, "label39");

  return excursion;
}

GtkWidget*
create_voiture (void)
{
  GtkWidget *voiture;
  GtkWidget *fixed7;
  GtkWidget *button16;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label74;
  GtkWidget *button21;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label105;
  GtkWidget *notebook2;
  GtkWidget *fixed8;
  GtkWidget *entry12;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *label84;
  GtkWidget *label77;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *label88;
  GtkWidget *label106;
  GtkWidget *button17;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label89;
  GtkWidget *label75;
  GtkWidget *label76;
  GtkWidget *label80;
  GtkWidget *combobox8;
  GtkWidget *label79;
  GtkWidget *label83;
  GtkWidget *combobox7;
  GtkWidget *label78;
  GtkWidget *label108;
  GtkWidget *label107;
  GtkWidget *label109;
  GtkWidget *label90;
  GtkWidget *fixed9;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkWidget *entry20;
  GtkWidget *entry21;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *label117;
  GtkWidget *label116;
  GtkWidget *label115;
  GtkWidget *label118;
  GtkWidget *label113;
  GtkWidget *button22;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label119;
  GtkWidget *button24;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label122;
  GtkWidget *label110;
  GtkWidget *label112;
  GtkWidget *label111;
  GtkWidget *label121;
  GtkWidget *button23;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label120;
  GtkWidget *combobox10;
  GtkWidget *combobox11;
  GtkWidget *label104;
  GtkWidget *fixed10;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview3;
  GtkWidget *entry22;
  GtkWidget *label124;
  GtkWidget *button25;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label125;
  GtkWidget *label126;
  GtkWidget *label128;
  GtkWidget *label127;
  GtkWidget *label123;

  voiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (voiture, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (voiture), _("Gestion Voiture"));
  gtk_window_set_position (GTK_WINDOW (voiture), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (voiture), FALSE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (voiture), fixed7);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed7), button16, 888, 648);
  gtk_widget_set_size_request (button16, 96, 53);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button16), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox16), label74, FALSE, FALSE, 0);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed7), button21, 16, 648);
  gtk_widget_set_size_request (button21, 96, 53);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button21), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label105 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label105);
  gtk_box_pack_start (GTK_BOX (hbox21), label105, FALSE, FALSE, 0);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed7), notebook2, 0, 8);
  gtk_widget_set_size_request (notebook2, 1016, 640);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed8);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed8), entry12, 272, 112);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  spinbutton7_adj = gtk_adjustment_new (200, 200, 1200, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton7, 312, 424);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  label84 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed8), label84, 32, 152);
  gtk_widget_set_size_request (label84, 128, 48);

  label77 = gtk_label_new (_("Matricule : "));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed8), label77, 64, 104);
  gtk_widget_set_size_request (label77, 80, 48);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed8), entry18, 272, 272);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed8), entry19, 272, 336);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  label88 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed8), label88, 48, 416);
  gtk_widget_set_size_request (label88, 120, 40);

  label106 = gtk_label_new (_("Couleur : "));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed8), label106, 56, 264);
  gtk_widget_set_size_request (label106, 80, 48);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed8), button17, 296, 512);
  gtk_widget_set_size_request (button17, 96, 53);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button17), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label89 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label89);
  gtk_box_pack_start (GTK_BOX (hbox17), label89, FALSE, FALSE, 0);

  label75 = gtk_label_new (_("<span foreground=\"blue\"><i>Voiture ajout\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label75, 40, 24);
  gtk_widget_set_size_request (label75, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label75), TRUE);

  label76 = gtk_label_new (_("<span foreground=\"red\"><b>Voiture existant!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label76, 320, 24);
  gtk_widget_set_size_request (label76, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label76), TRUE);

  label80 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Matricule !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label80, 440, 88);
  gtk_widget_set_size_request (label80, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label80), TRUE);

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox8, 272, 160);
  gtk_widget_set_size_request (combobox8, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("BMW"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Citroen"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Audi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Volkswagen"));

  label79 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Marque !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label79, 440, 136);
  gtk_widget_set_size_request (label79, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label79), TRUE);

  label83 = gtk_label_new (_("Carburant : "));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed8), label83, 24, 200);
  gtk_widget_set_size_request (label83, 128, 48);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox7, 272, 208);
  gtk_widget_set_size_request (combobox7, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Gazoil"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Essence"));

  label78 = gtk_label_new (_("<span foreground=\"red\"><b>Choisir Carburan !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label78, 448, 184);
  gtk_widget_set_size_request (label78, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label78), TRUE);

  label108 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Couleur !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label108, 440, 248);
  gtk_widget_set_size_request (label108, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label108), TRUE);

  label107 = gtk_label_new (_("Option : "));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed8), label107, 56, 328);
  gtk_widget_set_size_request (label107, 80, 48);

  label109 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Option !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed8), label109, 440, 320);
  gtk_widget_set_size_request (label109, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label109), TRUE);

  label90 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label90);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label90);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed9);

  spinbutton8_adj = gtk_adjustment_new (200, 200, 1200, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton8, 808, 344);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed9), entry20, 768, 208);
  gtk_widget_set_size_request (entry20, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed9), entry21, 768, 256);
  gtk_widget_set_size_request (entry21, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed9), scrolledwindow2, 0, 80);
  gtk_widget_set_size_request (scrolledwindow2, 584, 384);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);
  gtk_widget_set_size_request (treeview2, 584, 384);

  label117 = gtk_label_new (_("Carburant : "));
  gtk_widget_show (label117);
  gtk_fixed_put (GTK_FIXED (fixed9), label117, 632, 144);
  gtk_widget_set_size_request (label117, 128, 48);

  label116 = gtk_label_new (_("Couleur  : "));
  gtk_widget_show (label116);
  gtk_fixed_put (GTK_FIXED (fixed9), label116, 656, 200);
  gtk_widget_set_size_request (label116, 128, 48);

  label115 = gtk_label_new (_("Option : "));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed9), label115, 648, 248);
  gtk_widget_set_size_request (label115, 144, 48);

  label118 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed9), label118, 664, 336);
  gtk_widget_set_size_request (label118, 120, 40);

  label113 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed9), label113, 640, 96);
  gtk_widget_set_size_request (label113, 128, 48);

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed9), button22, 64, 512);
  gtk_widget_set_size_request (button22, 104, 56);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button22), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label119 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label119);
  gtk_box_pack_start (GTK_BOX (hbox22), label119, FALSE, FALSE, 0);

  button24 = gtk_button_new ();
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed9), button24, 320, 512);
  gtk_widget_set_size_request (button24, 104, 56);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button24), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label122 = gtk_label_new_with_mnemonic (_("Louer"));
  gtk_widget_show (label122);
  gtk_box_pack_start (GTK_BOX (hbox24), label122, FALSE, FALSE, 0);

  label110 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner une Voiture !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), label110, 0, 16);
  gtk_widget_set_size_request (label110, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label110), TRUE);

  label112 = gtk_label_new (_("Modifier la Voiture : "));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed9), label112, 656, 56);
  gtk_widget_set_size_request (label112, 152, 48);

  label111 = gtk_label_new (_("<span foreground=\"blue\"><i>Voiture modifi\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed9), label111, 664, 0);
  gtk_widget_set_size_request (label111, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label111), TRUE);

  label121 = gtk_label_new ("");
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed9), label121, 824, 56);
  gtk_widget_set_size_request (label121, 104, 48);

  button23 = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), button23, 760, 416);
  gtk_widget_set_size_request (button23, 96, 53);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button23), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label120 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label120);
  gtk_box_pack_start (GTK_BOX (hbox23), label120, FALSE, FALSE, 0);

  combobox10 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox10);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox10, 768, 104);
  gtk_widget_set_size_request (combobox10, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("BMW"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("Citroen"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("Audi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("Volkswagen"));

  combobox11 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox11);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox11, 768, 152);
  gtk_widget_set_size_request (combobox11, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox11), _("Gazoil"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox11), _("Essence"));

  label104 = gtk_label_new (_("Afficher/Supprimer/Modifier"));
  gtk_widget_show (label104);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label104);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed10);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed10), scrolledwindow3, 0, 48);
  gtk_widget_set_size_request (scrolledwindow3, 592, 344);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview3);
  gtk_widget_set_size_request (treeview3, 592, 344);

  entry22 = gtk_entry_new ();
  gtk_widget_show (entry22);
  gtk_fixed_put (GTK_FIXED (fixed10), entry22, 744, 160);
  gtk_widget_set_size_request (entry22, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  label124 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label124);
  gtk_fixed_put (GTK_FIXED (fixed10), label124, 600, 152);
  gtk_widget_set_size_request (label124, 128, 48);

  button25 = gtk_button_new ();
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed10), button25, 752, 360);
  gtk_widget_set_size_request (button25, 96, 53);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button25), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label125 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label125);
  gtk_box_pack_start (GTK_BOX (hbox25), label125, FALSE, FALSE, 0);

  label126 = gtk_label_new (_("<span foreground=\"red\"><b>Saisir Marque !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), label126, 680, 72);
  gtk_widget_set_size_request (label126, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label126), TRUE);

  label128 = gtk_label_new (_("<span foreground=\"brown\"><b>Resulta(s) trouv\303\251e(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed10), label128, 704, 216);
  gtk_widget_set_size_request (label128, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label128), TRUE);

  label127 = gtk_label_new ("");
  gtk_widget_show (label127);
  gtk_fixed_put (GTK_FIXED (fixed10), label127, 664, 224);
  gtk_widget_set_size_request (label127, 72, 56);

  label123 = gtk_label_new (_("Chercher"));
  gtk_widget_show (label123);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label123);

  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_VoitureAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_AjouterVoiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_SupprimerVoiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_LouerVoiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (on_ModifierVoiture_clicked),
                    NULL);
  g_signal_connect ((gpointer) button25, "clicked",
                    G_CALLBACK (on_ChercherVoiture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (voiture, voiture, "voiture");
  GLADE_HOOKUP_OBJECT (voiture, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (voiture, button16, "button16");
  GLADE_HOOKUP_OBJECT (voiture, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (voiture, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (voiture, image16, "image16");
  GLADE_HOOKUP_OBJECT (voiture, label74, "label74");
  GLADE_HOOKUP_OBJECT (voiture, button21, "button21");
  GLADE_HOOKUP_OBJECT (voiture, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (voiture, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (voiture, image21, "image21");
  GLADE_HOOKUP_OBJECT (voiture, label105, "label105");
  GLADE_HOOKUP_OBJECT (voiture, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (voiture, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (voiture, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (voiture, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (voiture, label84, "label84");
  GLADE_HOOKUP_OBJECT (voiture, label77, "label77");
  GLADE_HOOKUP_OBJECT (voiture, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (voiture, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (voiture, label88, "label88");
  GLADE_HOOKUP_OBJECT (voiture, label106, "label106");
  GLADE_HOOKUP_OBJECT (voiture, button17, "button17");
  GLADE_HOOKUP_OBJECT (voiture, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (voiture, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (voiture, image17, "image17");
  GLADE_HOOKUP_OBJECT (voiture, label89, "label89");
  GLADE_HOOKUP_OBJECT (voiture, label75, "label75");
  GLADE_HOOKUP_OBJECT (voiture, label76, "label76");
  GLADE_HOOKUP_OBJECT (voiture, label80, "label80");
  GLADE_HOOKUP_OBJECT (voiture, combobox8, "combobox8");
  GLADE_HOOKUP_OBJECT (voiture, label79, "label79");
  GLADE_HOOKUP_OBJECT (voiture, label83, "label83");
  GLADE_HOOKUP_OBJECT (voiture, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (voiture, label78, "label78");
  GLADE_HOOKUP_OBJECT (voiture, label108, "label108");
  GLADE_HOOKUP_OBJECT (voiture, label107, "label107");
  GLADE_HOOKUP_OBJECT (voiture, label109, "label109");
  GLADE_HOOKUP_OBJECT (voiture, label90, "label90");
  GLADE_HOOKUP_OBJECT (voiture, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (voiture, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (voiture, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (voiture, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (voiture, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (voiture, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (voiture, label117, "label117");
  GLADE_HOOKUP_OBJECT (voiture, label116, "label116");
  GLADE_HOOKUP_OBJECT (voiture, label115, "label115");
  GLADE_HOOKUP_OBJECT (voiture, label118, "label118");
  GLADE_HOOKUP_OBJECT (voiture, label113, "label113");
  GLADE_HOOKUP_OBJECT (voiture, button22, "button22");
  GLADE_HOOKUP_OBJECT (voiture, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (voiture, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (voiture, image22, "image22");
  GLADE_HOOKUP_OBJECT (voiture, label119, "label119");
  GLADE_HOOKUP_OBJECT (voiture, button24, "button24");
  GLADE_HOOKUP_OBJECT (voiture, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (voiture, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (voiture, image24, "image24");
  GLADE_HOOKUP_OBJECT (voiture, label122, "label122");
  GLADE_HOOKUP_OBJECT (voiture, label110, "label110");
  GLADE_HOOKUP_OBJECT (voiture, label112, "label112");
  GLADE_HOOKUP_OBJECT (voiture, label111, "label111");
  GLADE_HOOKUP_OBJECT (voiture, label121, "label121");
  GLADE_HOOKUP_OBJECT (voiture, button23, "button23");
  GLADE_HOOKUP_OBJECT (voiture, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (voiture, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (voiture, image23, "image23");
  GLADE_HOOKUP_OBJECT (voiture, label120, "label120");
  GLADE_HOOKUP_OBJECT (voiture, combobox10, "combobox10");
  GLADE_HOOKUP_OBJECT (voiture, combobox11, "combobox11");
  GLADE_HOOKUP_OBJECT (voiture, label104, "label104");
  GLADE_HOOKUP_OBJECT (voiture, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (voiture, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (voiture, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (voiture, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (voiture, label124, "label124");
  GLADE_HOOKUP_OBJECT (voiture, button25, "button25");
  GLADE_HOOKUP_OBJECT (voiture, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (voiture, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (voiture, image25, "image25");
  GLADE_HOOKUP_OBJECT (voiture, label125, "label125");
  GLADE_HOOKUP_OBJECT (voiture, label126, "label126");
  GLADE_HOOKUP_OBJECT (voiture, label128, "label128");
  GLADE_HOOKUP_OBJECT (voiture, label127, "label127");
  GLADE_HOOKUP_OBJECT (voiture, label123, "label123");

  return voiture;
}

