/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_wind4 (void)
{
  GtkWidget *wind4;
  GtkWidget *fixed1;
  GtkWidget *afficherfactures_client;
  GtkWidget *afficherdevis_client;
  GtkWidget *labelclient;

  wind4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wind4), _("wind4"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (wind4), fixed1);

  afficherfactures_client = gtk_button_new_with_mnemonic (_("AFFICHER MES FACTURES"));
  gtk_widget_show (afficherfactures_client);
  gtk_fixed_put (GTK_FIXED (fixed1), afficherfactures_client, 80, 152);
  gtk_widget_set_size_request (afficherfactures_client, 184, 88);

  afficherdevis_client = gtk_button_new_with_mnemonic (_("AFFICHER MES DEVIS"));
  gtk_widget_show (afficherdevis_client);
  gtk_fixed_put (GTK_FIXED (fixed1), afficherdevis_client, 80, 80);
  gtk_widget_set_size_request (afficherdevis_client, 184, 72);

  labelclient = gtk_label_new (_("<span foreground=\"black\" size=\"xx-large\"> <b> ESPACE CLIENT </b> </span>"));
  gtk_widget_show (labelclient);
  gtk_fixed_put (GTK_FIXED (fixed1), labelclient, 0, 8);
  gtk_widget_set_size_request (labelclient, 352, 72);
  gtk_label_set_use_markup (GTK_LABEL (labelclient), TRUE);

  g_signal_connect ((gpointer) afficherfactures_client, "clicked",
                    G_CALLBACK (on_afficherfactures_client_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficherdevis_client, "clicked",
                    G_CALLBACK (on_afficherdevis_client_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wind4, wind4, "wind4");
  GLADE_HOOKUP_OBJECT (wind4, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (wind4, afficherfactures_client, "afficherfactures_client");
  GLADE_HOOKUP_OBJECT (wind4, afficherdevis_client, "afficherdevis_client");
  GLADE_HOOKUP_OBJECT (wind4, labelclient, "labelclient");

  return wind4;
}

GtkWidget*
create_wind5 (void)
{
  GtkWidget *wind5;
  GtkWidget *fixed2;
  GtkWidget *treeview202;
  GtkWidget *entry230;
  GtkWidget *payer;
  GtkWidget *retourwind41;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label253;
  GtkWidget *supprimerdevis2;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label255;
  GtkWidget *label2;

  wind5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wind5), _("wind5"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (wind5), fixed2);

  treeview202 = gtk_tree_view_new ();
  gtk_widget_show (treeview202);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview202, 72, 72);
  gtk_widget_set_size_request (treeview202, 352, 200);

  entry230 = gtk_entry_new ();
  gtk_widget_show (entry230);
  gtk_fixed_put (GTK_FIXED (fixed2), entry230, 128, 288);
  gtk_widget_set_size_request (entry230, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry230), 8226);

  payer = gtk_button_new_with_mnemonic (_("payer"));
  gtk_widget_show (payer);
  gtk_fixed_put (GTK_FIXED (fixed2), payer, 288, 360);
  gtk_widget_set_size_request (payer, 82, 32);

  retourwind41 = gtk_button_new ();
  gtk_widget_show (retourwind41);
  gtk_fixed_put (GTK_FIXED (fixed2), retourwind41, 368, 360);
  gtk_widget_set_size_request (retourwind41, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (retourwind41), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label253 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label253);
  gtk_box_pack_start (GTK_BOX (hbox1), label253, FALSE, FALSE, 0);

  supprimerdevis2 = gtk_button_new ();
  gtk_widget_show (supprimerdevis2);
  gtk_fixed_put (GTK_FIXED (fixed2), supprimerdevis2, 304, 288);
  gtk_widget_set_size_request (supprimerdevis2, 104, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (supprimerdevis2), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label255 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label255);
  gtk_box_pack_start (GTK_BOX (hbox3), label255, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("<span foreground=\"black\" size=\"xx-large\"><b>MES DEVIS</b></span>"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 168, 8);
  gtk_widget_set_size_request (label2, 144, 48);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  g_signal_connect ((gpointer) payer, "clicked",
                    G_CALLBACK (on_payer_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourwind41, "clicked",
                    G_CALLBACK (on_retourwind41_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimerdevis2, "clicked",
                    G_CALLBACK (on_supprimerdevis2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wind5, wind5, "wind5");
  GLADE_HOOKUP_OBJECT (wind5, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (wind5, treeview202, "treeview202");
  GLADE_HOOKUP_OBJECT (wind5, entry230, "entry230");
  GLADE_HOOKUP_OBJECT (wind5, payer, "payer");
  GLADE_HOOKUP_OBJECT (wind5, retourwind41, "retourwind41");
  GLADE_HOOKUP_OBJECT (wind5, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (wind5, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (wind5, image1, "image1");
  GLADE_HOOKUP_OBJECT (wind5, label253, "label253");
  GLADE_HOOKUP_OBJECT (wind5, supprimerdevis2, "supprimerdevis2");
  GLADE_HOOKUP_OBJECT (wind5, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (wind5, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (wind5, image3, "image3");
  GLADE_HOOKUP_OBJECT (wind5, label255, "label255");
  GLADE_HOOKUP_OBJECT (wind5, label2, "label2");

  return wind5;
}

GtkWidget*
create_wind6 (void)
{
  GtkWidget *wind6;
  GtkWidget *fixed3;
  GtkWidget *treeview203;
  GtkWidget *entry231;
  GtkWidget *retourwind42;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label254;
  GtkWidget *supprimerfactures2;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label256;
  GtkWidget *label3;
  GtkWidget *label4;

  wind6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wind6), _("wind6"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (wind6), fixed3);

  treeview203 = gtk_tree_view_new ();
  gtk_widget_show (treeview203);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview203, 56, 48);
  gtk_widget_set_size_request (treeview203, 344, 232);

  entry231 = gtk_entry_new ();
  gtk_widget_show (entry231);
  gtk_fixed_put (GTK_FIXED (fixed3), entry231, 104, 320);
  gtk_widget_set_size_request (entry231, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry231), 8226);

  retourwind42 = gtk_button_new ();
  gtk_widget_show (retourwind42);
  gtk_fixed_put (GTK_FIXED (fixed3), retourwind42, 344, 368);
  gtk_widget_set_size_request (retourwind42, 80, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (retourwind42), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label254 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label254);
  gtk_box_pack_start (GTK_BOX (hbox2), label254, FALSE, FALSE, 0);

  supprimerfactures2 = gtk_button_new ();
  gtk_widget_show (supprimerfactures2);
  gtk_fixed_put (GTK_FIXED (fixed3), supprimerfactures2, 272, 320);
  gtk_widget_set_size_request (supprimerfactures2, 104, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (supprimerfactures2), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label256 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label256);
  gtk_box_pack_start (GTK_BOX (hbox4), label256, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("<span foreground=\"black\" size=\"xx-large\"><b>MES FACTURES</b></span>"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed3), label3, 96, 0);
  gtk_widget_set_size_request (label3, 224, 48);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  label4 = gtk_label_new (_("<span foreground=\"black\" background=\"lightblue\"><b>saisir l'dentifiant de la facture</b></span>"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 80, 288);
  gtk_widget_set_size_request (label4, 240, 24);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  g_signal_connect ((gpointer) retourwind42, "clicked",
                    G_CALLBACK (on_retourwind42_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimerfactures2, "clicked",
                    G_CALLBACK (on_supprimerfactures2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wind6, wind6, "wind6");
  GLADE_HOOKUP_OBJECT (wind6, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (wind6, treeview203, "treeview203");
  GLADE_HOOKUP_OBJECT (wind6, entry231, "entry231");
  GLADE_HOOKUP_OBJECT (wind6, retourwind42, "retourwind42");
  GLADE_HOOKUP_OBJECT (wind6, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (wind6, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (wind6, image2, "image2");
  GLADE_HOOKUP_OBJECT (wind6, label254, "label254");
  GLADE_HOOKUP_OBJECT (wind6, supprimerfactures2, "supprimerfactures2");
  GLADE_HOOKUP_OBJECT (wind6, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (wind6, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (wind6, image4, "image4");
  GLADE_HOOKUP_OBJECT (wind6, label256, "label256");
  GLADE_HOOKUP_OBJECT (wind6, label3, "label3");
  GLADE_HOOKUP_OBJECT (wind6, label4, "label4");

  return wind6;
}

GtkWidget*
create_wind7 (void)
{
  GtkWidget *wind7;
  GtkWidget *fixed4;
  GtkWidget *entry250;
  GtkWidget *entry251;
  GtkWidget *entry252;
  GtkWidget *entry253;
  GtkWidget *label7;
  GtkWidget *label11;
  GtkWidget *devispaye;
  GtkWidget *label251;
  GtkWidget *confirmer250;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label257;
  GtkWidget *retourwind43;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label258;
  GtkWidget *recherche_dev_pay;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label259;
  GtkWidget *label250;
  GtkWidget *label252;
  GtkWidget *label6;

  wind7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wind7), _("wind7"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (wind7), fixed4);

  entry250 = gtk_entry_new ();
  gtk_widget_show (entry250);
  gtk_fixed_put (GTK_FIXED (fixed4), entry250, 312, 64);
  gtk_widget_set_size_request (entry250, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry250), 8226);

  entry251 = gtk_entry_new ();
  gtk_widget_show (entry251);
  gtk_fixed_put (GTK_FIXED (fixed4), entry251, 312, 160);
  gtk_widget_set_size_request (entry251, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry251), 8226);

  entry252 = gtk_entry_new ();
  gtk_widget_show (entry252);
  gtk_fixed_put (GTK_FIXED (fixed4), entry252, 312, 200);
  gtk_widget_set_size_request (entry252, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry252), 8226);

  entry253 = gtk_entry_new ();
  gtk_widget_show (entry253);
  gtk_fixed_put (GTK_FIXED (fixed4), entry253, 312, 248);
  gtk_widget_set_size_request (entry253, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry253), 8226);

  label7 = gtk_label_new (_("<span foreground=\"black\" background=\"lightblue\"><b> LE NUM\303\211RO DE VOTRE CARTE BANCAIRE: </b></span>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed4), label7, 0, 160);
  gtk_widget_set_size_request (label7, 312, 24);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label11 = gtk_label_new (_("<b>montant \303\240 payer en DT:</b> "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed4), label11, 32, 104);
  gtk_widget_set_size_request (label11, 168, 24);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  devispaye = gtk_label_new (_("<span foreground=\"black\" background=\"lightblue\"><b>L'IDENTIFIANT DU DEVIS A PAYER</b></span>"));
  gtk_widget_show (devispaye);
  gtk_fixed_put (GTK_FIXED (fixed4), devispaye, 8, 64);
  gtk_widget_set_size_request (devispaye, 256, 24);
  gtk_label_set_use_markup (GTK_LABEL (devispaye), TRUE);

  label251 = gtk_label_new (_("<span foreground=\"black\" background=\"lightblue\" ><b>date d'expiration:</b></span>"));
  gtk_widget_show (label251);
  gtk_fixed_put (GTK_FIXED (fixed4), label251, 128, 200);
  gtk_widget_set_size_request (label251, 184, 32);
  gtk_label_set_use_markup (GTK_LABEL (label251), TRUE);

  confirmer250 = gtk_button_new ();
  gtk_widget_show (confirmer250);
  gtk_fixed_put (GTK_FIXED (fixed4), confirmer250, 296, 304);
  gtk_widget_set_size_request (confirmer250, 96, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (confirmer250), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label257 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label257);
  gtk_box_pack_start (GTK_BOX (hbox5), label257, FALSE, FALSE, 0);

  retourwind43 = gtk_button_new ();
  gtk_widget_show (retourwind43);
  gtk_fixed_put (GTK_FIXED (fixed4), retourwind43, 392, 304);
  gtk_widget_set_size_request (retourwind43, 80, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (retourwind43), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label258 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label258);
  gtk_box_pack_start (GTK_BOX (hbox6), label258, FALSE, FALSE, 0);

  recherche_dev_pay = gtk_button_new ();
  gtk_widget_show (recherche_dev_pay);
  gtk_fixed_put (GTK_FIXED (fixed4), recherche_dev_pay, 480, 64);
  gtk_widget_set_size_request (recherche_dev_pay, 96, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (recherche_dev_pay), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label259 = gtk_label_new_with_mnemonic (_("recherche"));
  gtk_widget_show (label259);
  gtk_box_pack_start (GTK_BOX (hbox7), label259, FALSE, FALSE, 0);

  label250 = gtk_label_new ("");
  gtk_widget_show (label250);
  gtk_fixed_put (GTK_FIXED (fixed4), label250, 200, 96);
  gtk_widget_set_size_request (label250, 408, 48);

  label252 = gtk_label_new (_("<span foreground=\"black\" background=\"lightblue\"><b> mot de passe:</b></span>"));
  gtk_widget_show (label252);
  gtk_fixed_put (GTK_FIXED (fixed4), label252, 120, 248);
  gtk_widget_set_size_request (label252, 184, 24);
  gtk_label_set_use_markup (GTK_LABEL (label252), TRUE);

  label6 = gtk_label_new (_("<span foreground=\"black\" size=\"xx-large\"><b><u>PAIEMENT</u></b></span>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed4), label6, 224, 8);
  gtk_widget_set_size_request (label6, 144, 32);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  g_signal_connect ((gpointer) confirmer250, "clicked",
                    G_CALLBACK (on_confirmer250_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourwind43, "clicked",
                    G_CALLBACK (on_retourwind43_clicked),
                    NULL);
  g_signal_connect ((gpointer) recherche_dev_pay, "clicked",
                    G_CALLBACK (on_recherche_dev_pay_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wind7, wind7, "wind7");
  GLADE_HOOKUP_OBJECT (wind7, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (wind7, entry250, "entry250");
  GLADE_HOOKUP_OBJECT (wind7, entry251, "entry251");
  GLADE_HOOKUP_OBJECT (wind7, entry252, "entry252");
  GLADE_HOOKUP_OBJECT (wind7, entry253, "entry253");
  GLADE_HOOKUP_OBJECT (wind7, label7, "label7");
  GLADE_HOOKUP_OBJECT (wind7, label11, "label11");
  GLADE_HOOKUP_OBJECT (wind7, devispaye, "devispaye");
  GLADE_HOOKUP_OBJECT (wind7, label251, "label251");
  GLADE_HOOKUP_OBJECT (wind7, confirmer250, "confirmer250");
  GLADE_HOOKUP_OBJECT (wind7, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (wind7, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (wind7, image5, "image5");
  GLADE_HOOKUP_OBJECT (wind7, label257, "label257");
  GLADE_HOOKUP_OBJECT (wind7, retourwind43, "retourwind43");
  GLADE_HOOKUP_OBJECT (wind7, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (wind7, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (wind7, image6, "image6");
  GLADE_HOOKUP_OBJECT (wind7, label258, "label258");
  GLADE_HOOKUP_OBJECT (wind7, recherche_dev_pay, "recherche_dev_pay");
  GLADE_HOOKUP_OBJECT (wind7, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (wind7, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (wind7, image7, "image7");
  GLADE_HOOKUP_OBJECT (wind7, label259, "label259");
  GLADE_HOOKUP_OBJECT (wind7, label250, "label250");
  GLADE_HOOKUP_OBJECT (wind7, label252, "label252");
  GLADE_HOOKUP_OBJECT (wind7, label6, "label6");

  return wind7;
}

