/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout_client (void)
{
  GtkWidget *ajout_client;
  GtkWidget *fixed1;
  GtkWidget *entry100;
  GtkWidget *entry101;
  GtkWidget *entry103;
  GtkWidget *entry104;
  GtkWidget *entry105;
  GtkWidget *label100;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label104;
  GtkWidget *label105;
  GtkWidget *label106;
  GtkWidget *image3;
  GtkWidget *ajouter_reclamation;
  GtkWidget *afficher_treeview1;
  GtkWidget *label112;
  GtkWidget *retourw1;

  ajout_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_client), _("ajout_client"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajout_client), fixed1);

  entry100 = gtk_entry_new ();
  gtk_widget_show (entry100);
  gtk_fixed_put (GTK_FIXED (fixed1), entry100, 152, 72);
  gtk_widget_set_size_request (entry100, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry100), 8226);

  entry101 = gtk_entry_new ();
  gtk_widget_show (entry101);
  gtk_fixed_put (GTK_FIXED (fixed1), entry101, 152, 136);
  gtk_widget_set_size_request (entry101, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry101), 8226);

  entry103 = gtk_entry_new ();
  gtk_widget_show (entry103);
  gtk_fixed_put (GTK_FIXED (fixed1), entry103, 152, 192);
  gtk_widget_set_size_request (entry103, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry103), 8226);

  entry104 = gtk_entry_new ();
  gtk_widget_show (entry104);
  gtk_fixed_put (GTK_FIXED (fixed1), entry104, 152, 248);
  gtk_widget_set_size_request (entry104, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry104), 8226);

  entry105 = gtk_entry_new ();
  gtk_widget_show (entry105);
  gtk_fixed_put (GTK_FIXED (fixed1), entry105, 152, 312);
  gtk_widget_set_size_request (entry105, 300, 100);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry105), 8226);

  label100 = gtk_label_new (_("RECLAMATION"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed1), label100, 160, 8);
  gtk_widget_set_size_request (label100, 200, 17);

  label101 = gtk_label_new (_("ID_client"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed1), label101, 16, 80);
  gtk_widget_set_size_request (label101, 100, 17);

  label102 = gtk_label_new (_("ID_reclamation"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed1), label102, 32, 136);
  gtk_widget_set_size_request (label102, 110, 17);

  label104 = gtk_label_new (_("Date_reclamation"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed1), label104, 24, 192);
  gtk_widget_set_size_request (label104, 136, 24);

  label105 = gtk_label_new (_("prestation"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed1), label105, 32, 248);
  gtk_widget_set_size_request (label105, 80, 17);

  label106 = gtk_label_new (_("Reclamation :"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed1), label106, 32, 312);
  gtk_widget_set_size_request (label106, 100, 17);

  image3 = create_pixmap (ajout_client, "index.jpeg");
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed1), image3, 120, 560);
  gtk_widget_set_size_request (image3, 288, 176);

  ajouter_reclamation = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (ajouter_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter_reclamation, 304, 432);
  gtk_widget_set_size_request (ajouter_reclamation, 66, 29);

  afficher_treeview1 = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (afficher_treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher_treeview1, 224, 432);
  gtk_widget_set_size_request (afficher_treeview1, 66, 29);

  label112 = gtk_label_new ("");
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed1), label112, 40, 472);
  gtk_widget_set_size_request (label112, 456, 64);

  retourw1 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (retourw1);
  gtk_fixed_put (GTK_FIXED (fixed1), retourw1, 384, 432);
  gtk_widget_set_size_request (retourw1, 66, 29);

  g_signal_connect ((gpointer) ajouter_reclamation, "clicked",
                    G_CALLBACK (on_ajouter_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher_treeview1, "clicked",
                    G_CALLBACK (on_afficher_treeview1_clicked),
                    NULL);
  g_signal_connect ((gpointer) retourw1, "clicked",
                    G_CALLBACK (on_retourw1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_client, ajout_client, "ajout_client");
  GLADE_HOOKUP_OBJECT (ajout_client, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajout_client, entry100, "entry100");
  GLADE_HOOKUP_OBJECT (ajout_client, entry101, "entry101");
  GLADE_HOOKUP_OBJECT (ajout_client, entry103, "entry103");
  GLADE_HOOKUP_OBJECT (ajout_client, entry104, "entry104");
  GLADE_HOOKUP_OBJECT (ajout_client, entry105, "entry105");
  GLADE_HOOKUP_OBJECT (ajout_client, label100, "label100");
  GLADE_HOOKUP_OBJECT (ajout_client, label101, "label101");
  GLADE_HOOKUP_OBJECT (ajout_client, label102, "label102");
  GLADE_HOOKUP_OBJECT (ajout_client, label104, "label104");
  GLADE_HOOKUP_OBJECT (ajout_client, label105, "label105");
  GLADE_HOOKUP_OBJECT (ajout_client, label106, "label106");
  GLADE_HOOKUP_OBJECT (ajout_client, image3, "image3");
  GLADE_HOOKUP_OBJECT (ajout_client, ajouter_reclamation, "ajouter_reclamation");
  GLADE_HOOKUP_OBJECT (ajout_client, afficher_treeview1, "afficher_treeview1");
  GLADE_HOOKUP_OBJECT (ajout_client, label112, "label112");
  GLADE_HOOKUP_OBJECT (ajout_client, retourw1, "retourw1");

  return ajout_client;
}

GtkWidget*
create_affichage_client (void)
{
  GtkWidget *affichage_client;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *entry106;
  GtkWidget *supprimer;
  GtkWidget *recherche_reclamation;
  GtkWidget *image2;
  GtkWidget *label113;
  GtkWidget *retour1_reclamation;

  affichage_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage_client), _("affichage_client"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (affichage_client), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 64, 56);
  gtk_widget_set_size_request (treeview1, 464, 192);

  label107 = gtk_label_new (_("MES RECLAMATIONS"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed2), label107, 168, 16);
  gtk_widget_set_size_request (label107, 150, 17);

  label108 = gtk_label_new (_("ID_reclamation"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed2), label108, 48, 328);
  gtk_widget_set_size_request (label108, 120, 17);

  entry106 = gtk_entry_new ();
  gtk_widget_show (entry106);
  gtk_fixed_put (GTK_FIXED (fixed2), entry106, 168, 328);
  gtk_widget_set_size_request (entry106, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry106), 8226);

  supprimer = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), supprimer, 344, 328);
  gtk_widget_set_size_request (supprimer, 80, 29);
  gtk_button_set_focus_on_click (GTK_BUTTON (supprimer), FALSE);

  recherche_reclamation = gtk_button_new_with_mnemonic (_("recherche"));
  gtk_widget_show (recherche_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), recherche_reclamation, 232, 264);
  gtk_widget_set_size_request (recherche_reclamation, 80, 29);

  image2 = create_pixmap (affichage_client, "index.jpeg");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed2), image2, 112, 416);
  gtk_widget_set_size_request (image2, 344, 176);

  label113 = gtk_label_new ("");
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed2), label113, 80, 368);
  gtk_widget_set_size_request (label113, 360, 32);

  retour1_reclamation = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (retour1_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed2), retour1_reclamation, 320, 264);
  gtk_widget_set_size_request (retour1_reclamation, 66, 29);

  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) recherche_reclamation, "clicked",
                    G_CALLBACK (on_recherche_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour1_reclamation, "clicked",
                    G_CALLBACK (on_retour1_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage_client, affichage_client, "affichage_client");
  GLADE_HOOKUP_OBJECT (affichage_client, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (affichage_client, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (affichage_client, label107, "label107");
  GLADE_HOOKUP_OBJECT (affichage_client, label108, "label108");
  GLADE_HOOKUP_OBJECT (affichage_client, entry106, "entry106");
  GLADE_HOOKUP_OBJECT (affichage_client, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (affichage_client, recherche_reclamation, "recherche_reclamation");
  GLADE_HOOKUP_OBJECT (affichage_client, image2, "image2");
  GLADE_HOOKUP_OBJECT (affichage_client, label113, "label113");
  GLADE_HOOKUP_OBJECT (affichage_client, retour1_reclamation, "retour1_reclamation");

  return affichage_client;
}

GtkWidget*
create_afficher1_une_reclamation (void)
{
  GtkWidget *afficher1_une_reclamation;
  GtkWidget *fixed3;
  GtkWidget *entry107;
  GtkWidget *label109;
  GtkWidget *label111;
  GtkWidget *entry108;
  GtkWidget *modifier;
  GtkWidget *label110;
  GtkWidget *rechercher2_reclamation;
  GtkWidget *image1;
  GtkWidget *retour2_reclamation;
  GtkWidget *label114;

  afficher1_une_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher1_une_reclamation), _("afficher1_une_reclamation"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (afficher1_une_reclamation), fixed3);

  entry107 = gtk_entry_new ();
  gtk_widget_show (entry107);
  gtk_fixed_put (GTK_FIXED (fixed3), entry107, 272, 8);
  gtk_widget_set_size_request (entry107, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry107), 8226);

  label109 = gtk_label_new (_("ID_reclamation"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed3), label109, 144, 8);
  gtk_widget_set_size_request (label109, 121, 17);

  label111 = gtk_label_new (_("modification"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed3), label111, 16, 217);
  gtk_widget_set_size_request (label111, 104, 16);

  entry108 = gtk_entry_new ();
  gtk_widget_show (entry108);
  gtk_fixed_put (GTK_FIXED (fixed3), entry108, 120, 224);
  gtk_widget_set_size_request (entry108, 416, 100);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry108), 8226);

  modifier = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), modifier, 376, 328);
  gtk_widget_set_size_request (modifier, 72, 29);

  label110 = gtk_label_new ("");
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed3), label110, 64, 65);
  gtk_widget_set_size_request (label110, 536, 100);

  rechercher2_reclamation = gtk_button_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (rechercher2_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), rechercher2_reclamation, 432, 8);
  gtk_widget_set_size_request (rechercher2_reclamation, 88, 29);

  image1 = create_pixmap (afficher1_une_reclamation, "index.jpeg");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed3), image1, 128, 416);
  gtk_widget_set_size_request (image1, 344, 176);

  retour2_reclamation = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (retour2_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), retour2_reclamation, 448, 328);
  gtk_widget_set_size_request (retour2_reclamation, 66, 29);

  label114 = gtk_label_new ("");
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed3), label114, 96, 360);
  gtk_widget_set_size_request (label114, 448, 32);

  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) rechercher2_reclamation, "clicked",
                    G_CALLBACK (on_rechercher2_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour2_reclamation, "clicked",
                    G_CALLBACK (on_retour2_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher1_une_reclamation, afficher1_une_reclamation, "afficher1_une_reclamation");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, entry107, "entry107");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, label109, "label109");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, label111, "label111");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, entry108, "entry108");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, label110, "label110");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, rechercher2_reclamation, "rechercher2_reclamation");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, image1, "image1");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, retour2_reclamation, "retour2_reclamation");
  GLADE_HOOKUP_OBJECT (afficher1_une_reclamation, label114, "label114");

  return afficher1_une_reclamation;
}

GtkWidget*
create_w1 (void)
{
  GtkWidget *w1;
  GtkWidget *fixed4;
  GtkWidget *mesreclamation;
  GtkWidget *ajout_reclamation;

  w1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (w1, 400, 300);
  gtk_window_set_title (GTK_WINDOW (w1), _("w1"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (w1), fixed4);

  mesreclamation = gtk_button_new_with_mnemonic (_("Mes reclamations"));
  gtk_widget_show (mesreclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), mesreclamation, 112, 64);
  gtk_widget_set_size_request (mesreclamation, 176, 48);

  ajout_reclamation = gtk_button_new_with_mnemonic (_("Nouvelle reclamation"));
  gtk_widget_show (ajout_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed4), ajout_reclamation, 112, 152);
  gtk_widget_set_size_request (ajout_reclamation, 176, 48);

  g_signal_connect ((gpointer) mesreclamation, "clicked",
                    G_CALLBACK (on_mesreclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_reclamation, "clicked",
                    G_CALLBACK (on_ajout_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (w1, w1, "w1");
  GLADE_HOOKUP_OBJECT (w1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (w1, mesreclamation, "mesreclamation");
  GLADE_HOOKUP_OBJECT (w1, ajout_reclamation, "ajout_reclamation");

  return w1;
}

