/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout_client (void);
GtkWidget* create_affichage_client (void);
GtkWidget* create_afficher1_une_reclamation (void);
GtkWidget* create_w1 (void);
